### ISSUE TITLE
Missing submodules

### ISSUE THREAD

**Issue by animeavi** [ourfavoritefruits/citra-nightly#1]
### Issue

The Citra repo used submodules owned by the "citra-emu" organization on GitHub, unless someone has a copy of those you'd have a hard time compiling this. 

If you or or someone else cloned the repo locally (with --recurse-submodules) they will be located in the "extenals" folder and can be restored.  

- https://github.com/citra-emu/ext-boost
(as externals/boost)

- https://github.com/citra-emu/ext-libressl-portable
(as externals/libressl)

- https://github.com/citra-emu/ext-library-headers
(as externals/library-headers)

- https://github.com/yuzu-emu/discord-rpc.git
(as externals/discord-rpc)

- https://github.com/yuzu-emu/sirit
(as externals/sirit)

- https://github.com/merryhime/dynarmic.git
(as externals/dynarmic)

**Mirrors with commit history**
https://github.com/PabloMK7/ext-boost
https://github.com/PabloMK7/ext-libressl-portable
https://github.com/PabloMK7/ext-library-headers
https://github.com/PabloMK7/discord-rpc
https://github.com/PabloMK7/sirit
https://github.com/yuzu-mirror/dynarmic

**Alternative**:

Found a copy of just the files (meaning no commit history) on the Wayback Machine:
https://web.archive.org/web/20240228005437mp_/https://github.com/citra-emu/ext-boost/archive/refs/heads/master.zip
https://web.archive.org/web/20240228021543mp_/https://github.com/citra-emu/ext-libressl-portable/archive/refs/heads/master.zip
https://web.archive.org/web/20240228014147mp_/https://github.com/citra-emu/ext-library-headers/archive/refs/heads/main.zip
https://web.archive.org/web/20240227231523mp_/https://github.com/yuzu-emu/discord-rpc/archive/refs/heads/master.zip
https://web.archive.org/web/20240227234439mp_/https://github.com/yuzu-emu/sirit/archive/refs/heads/master.zip
https://web.archive.org/web/20240228002125mp_/https://github.com/merryhime/dynarmic/archive/refs/heads/master.zip

**Comment by ourfavoritefruits** [comment]
Sorry about that.
You should be able to compile it now.

**Comment by wings110** [comment]
https://github.com/citra-emu/ext-soundtouch.git  also miss this submodules

**Comment by wings110** [comment]
add this [submodule "soundtouch"]
    path = externals/soundtouch
    url = https://codeberg.org/soundtouch/soundtouch.git
show error
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
fatal: remote error: upload-pack: not our ref 060181eaf273180d3a7e87349895bd0cb6ccbf4a
fatal: Fetched in submodule path 'externals/soundtouch', but it did not contain 060181eaf273180d3a7e87349895bd0cb6ccbf4a. Direct fetching of that commit failed.
fatal: 
*********** FAILED COMMAND ***********
. "${get_handler}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/get "${PKG_NAME}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
**************************************
I can't figure out where 060181eaf273180d3a7e87349895bd0cb6ccbf4a comes from. I cannot find any reference to it anywhere, but I might not know where to look. Any assistance?
